# Generated by gallery/generate.py; do not edit.
forceload add 160 160 208 208
function supplementaries_gallery:clear
fill 172 100 173 203 100 203 minecraft:smooth_stone
setblock 176 104 186 minecraft:polished_andesite
setblock 181 101 177 minecraft:polished_andesite
setblock 181 102 196 minecraft:polished_andesite
setblock 186 101 182 minecraft:polished_andesite
setblock 196 101 177 minecraft:polished_andesite
setblock 196 101 187 minecraft:polished_andesite
setblock 196 102 181 minecraft:polished_andesite
setblock 201 101 182 minecraft:polished_andesite
setblock 201 101 187 minecraft:polished_andesite
setblock 201 101 192 minecraft:polished_andesite
setblock 173 101 176 minecraft:oak_sign[rotation=12,waterlogged=false]{front_text:{messages:['{"text":"CUSTOM MODELS"}','{"text":"SIGNS TO BOOKS"}','{"text":""}','{"text":""}']}}
setblock 173 101 181 minecraft:oak_sign[rotation=12,waterlogged=false]{front_text:{messages:['{"text":"CUSTOM MODELS"}','{"text":"GOBLET TO AWNING"}','{"text":""}','{"text":""}']}}
setblock 173 101 186 minecraft:oak_sign[rotation=12,waterlogged=false]{front_text:{messages:['{"text":"ROPES FRAMES"}','{"text":"ITEM DISPLAYS"}','{"text":""}','{"text":""}']}}
setblock 173 101 191 minecraft:oak_sign[rotation=12,waterlogged=false]{front_text:{messages:['{"text":"DISPLAY BERS"}','{"text":"GLOBES CLOCK"}','{"text":""}','{"text":""}']}}
setblock 173 101 196 minecraft:oak_sign[rotation=12,waterlogged=false]{front_text:{messages:['{"text":"CLOTH OBJECTS"}','{"text":"CAGE TO VANE"}','{"text":""}','{"text":""}']}}
setblock 173 101 201 minecraft:oak_sign[rotation=12,waterlogged=false]{front_text:{messages:['{"text":"OTHER BERS"}','{"text":"STATUE TO HEAD"}','{"text":""}','{"text":""}']}}
# way-sign: seeded standing oak and spruce signpost
setblock 176 101 176 supplementaries:way_sign
data merge block 176 101 176 {Mimic:{Name:"minecraft:oak_fence"},SignUp:{Active:1b,Left:0b,Yaw:0.0f,WoodType:"minecraft:oak"},SignDown:{Active:1b,Left:1b,Yaw:180.0f,WoodType:"minecraft:spruce"}}
# way-sign-wall: seeded wall signpost
setblock 181 101 176 supplementaries:way_sign_wall
data merge block 181 101 176 {Mimic:{Name:"minecraft:stone_bricks"},SignUp:{Active:1b,Left:0b,Yaw:90.0f,WoodType:"minecraft:birch"},SignDown:{Active:0b,Left:0b,Yaw:0.0f,WoodType:"minecraft:oak"}}
# flower-box: floor flower box with three plants
setblock 186 101 176 supplementaries:flower_box[facing=north,face=floor]
item replace block 186 101 176 container.0 with minecraft:poppy
item replace block 186 101 176 container.1 with minecraft:blue_orchid
item replace block 186 101 176 container.2 with minecraft:fern
# jar-empty: empty jar glass model
setblock 191 101 176 supplementaries:jar
# blackboard-pattern: blackboard with deterministic chalk X
setblock 196 101 176 supplementaries:blackboard[facing=north]
data merge block 196 101 176 {Pixels:[L;1152921504606846977L,72057594037927952L,4503599627370752L,281474976714752L,17592186109952L,1099512676352L,68736253952L,4563402752L,4563402752L,68736253952L,1099512676352L,17592186109952L,281474976714752L,4503599627370752L,72057594037927952L,1152921504606846977L],Waxed:1b}
# book-pile: upright book pile
setblock 201 101 176 supplementaries:book_pile
item replace block 201 101 176 container.0 with minecraft:enchanted_book
# book-pile-horizontal: horizontal book pile
setblock 176 101 181 supplementaries:book_pile_horizontal
item replace block 176 101 181 container.0 with minecraft:written_book
# goblet-empty: empty goblet custom model
setblock 181 101 181 supplementaries:goblet
# faucet-on: enabled faucet with water state
setblock 186 101 181 supplementaries:faucet[facing=north,enabled=true,connected=false,powered=false,has_water=true]
# rope-knot-mimic: rope knot around an oak fence
setblock 191 101 181 supplementaries:rope_knot[axis=y,type=post,up=true,down=true]
data merge block 191 101 181 {Mimic:{Name:"minecraft:oak_fence"}}
# rope-buntings: rope bunting custom model
setblock 196 101 181 supplementaries:rope_buntings[up=true]
# awning-slanted: red slanted awning extra rotation
setblock 201 101 181 supplementaries:awning_red[slanted=true,facing=north,bottom=true]
# rope-top: connected vertical rope top
setblock 176 103 186 supplementaries:rope[up=true,down=true]
# rope-middle: connected vertical rope middle
setblock 176 102 186 supplementaries:rope[up=true,down=true]
# rope-bottom: connected vertical rope bottom knot
setblock 176 101 186 supplementaries:rope[up=true,down=false,knot=true]
# timber-frame-mimic: brick-filled timber frame
setblock 181 101 186 supplementaries:timber_frame[has_block=true]
data merge block 181 101 186 {Mimic:{Name:"minecraft:bricks"}}
# timber-brace-mimic: deepslate-filled timber brace
setblock 186 101 186 supplementaries:timber_brace[has_block=true,flipped=false]
data merge block 186 101 186 {Mimic:{Name:"minecraft:deepslate_tiles"}}
# timber-cross-brace-mimic: mossy-filled timber cross brace
setblock 191 101 186 supplementaries:timber_cross_brace[has_block=true]
data merge block 191 101 186 {Mimic:{Name:"minecraft:mossy_cobblestone"}}
# item-shelf: item shelf with diamond sword
setblock 196 101 186 supplementaries:item_shelf[facing=north]
item replace block 196 101 186 container.0 with minecraft:diamond_sword
# notice-board: notice board with writable book
setblock 201 101 186 supplementaries:notice_board[facing=north,has_book=true]
item replace block 201 101 186 container.0 with minecraft:writable_book
# pedestal: pedestal with diamond
setblock 176 101 191 supplementaries:pedestal
item replace block 176 101 191 container.0 with minecraft:diamond
# crystal-display: fully powered crystal display
setblock 181 101 191 supplementaries:crystal_display[power=15,facing=north]
# globe: standard globe
setblock 186 101 191 supplementaries:globe[facing=north]
# globe-sepia: sepia globe
setblock 191 101 191 supplementaries:globe_sepia[facing=north]
# hourglass: sand-filled upright hourglass
setblock 196 101 191 supplementaries:hourglass[facing=up]
item replace block 196 101 191 container.0 with minecraft:sand
# clock-two-faced: two-faced wall clock
setblock 201 101 191 supplementaries:clock_block[facing=north,two_faced=true]
# flag-red: red flag cloth
setblock 176 101 196 supplementaries:flag_red
# bunting-red: red ceiling bunting
setblock 181 101 196 supplementaries:bunting_red[axis=x]
# cage-empty: empty cage
setblock 186 101 196 supplementaries:cage
# cannon: neutral cannon
setblock 191 101 196 supplementaries:cannon
# doormat: plain doormat
setblock 196 101 196 supplementaries:doormat[facing=north]
# wind-vane: neutral wind vane
setblock 201 101 196 supplementaries:wind_vane
# statue: default statue
setblock 176 101 201 supplementaries:statue[facing=north]
# bellows: neutral bellows
setblock 181 101 201 supplementaries:bellows
# bubble-block: bubble block renderer
setblock 186 101 201 supplementaries:bubble_block
# jar-boat: jar boat
setblock 191 101 201 supplementaries:jar_boat[facing=north]
# urn: empty urn
setblock 196 101 201 supplementaries:urn
# enderman-head: enderman head with eye renderer
setblock 201 101 201 supplementaries:enderman_head
function supplementaries_gallery:verify
